# Generated by Django 2.2.20 on 2021-06-21 09:20
import django.db.models.deletion
from django.db import migrations, models
from django.db.models.indexes import Index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsistencyFail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now_add=True)),
                ("resolved_on", models.DateTimeField(null=True)),
                ("validator_name", models.CharField(max_length=500)),
                ("object_id", models.PositiveIntegerField()),
                ("message", models.TextField()),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            "ConsistencyFail",
            Index(
                fields=["validator_name", "object_id", "resolved_on"],
                name="consistency_fail_vor",
            ),
        ),
    ]
